# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze --fatal-infos

      - name: Run tests
        run: flutter test

  example-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install plugin dependencies
        run: dart pub get

      - name: Install example dependencies
        run: |
          cd example
          flutter pub get

      - name: Verify example formatting
        run: |
          cd example
          dart format --output=none --set-exit-if-changed .

      - name: Analyze example project
        run: |
          cd example
          dart analyze --fatal-infos

      - name: Run example tests
        run: |
          cd example
          if [ -d "test" ] && [ "$(find test -name '*.dart' | wc -l)" -gt 0 ]; then
            flutter test
          else
            echo "No tests found in example/test directory, skipping..."
          fi

  android-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Android unit tests
        run: |
          cd android
          ./gradlew test

  android-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install plugin dependencies
        run: dart pub get

      - name: Install example dependencies
        run: |
          cd example
          flutter pub get

      - name: Build example (Android)
        run: |
          cd example
          flutter build apk --debug

  ios-build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install plugin dependencies
        run: dart pub get

      - name: Install example dependencies
        run: |
          cd example
          flutter pub get

      - name: Build iOS (example)
        run: |
          cd example
          flutter build ios --debug --no-codesign