name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Verify formatting
      run: dart format --output=none --set-exit-if-changed .

    - name: Analyze project source
      run: dart analyze --fatal-infos

    - name: Run Dart tests
      run: flutter test

    - name: Install dependencies (example)
      run: |
        cd example
        flutter pub get

    - name: Verify formatting (example)
      run: |
        cd example
        dart format --output=none --set-exit-if-changed .

    - name: Analyze example project
      run: |
        cd example
        dart analyze --fatal-infos

    - name: Build example (Android)
      run: |
        cd example
        flutter build apk --debug

  android-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Run Android unit tests
      run: |
        # Create a Gradle wrapper for the plugin
        cd android
        gradle wrapper
        ./gradlew test

  ios-build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Install dependencies (example)
      run: |
        cd example
        flutter pub get

    - name: Build iOS (example)
      run: |
        cd example
        flutter build ios --no-codesign